[[input]]
name = "Oslo, Norway"
src = "http://193.213.211.188:80/mjpg/video.mjpg"
uuid = "e7472d3c-f072-4cdd-be98-e4a3d717beeb"
loop = true

[[input]]
name = "Valencia, Spain"
src = "http://79.108.238.98:9000/mjpg/video.mjpg"
uuid = "95d6cb6b-99f7-4ca0-9afc-86bbe63afa35"
loop = false

[[input]]
name = "Lexington-Fayette, United States"
src = "http://64.191.148.57:80/mjpg/video.mjpg"
uuid = "bb962ecd-f3d8-4d25-b835-544e8f6df5af"
loop = false

[[input]]
name = "Gatwick, United Kingdom"
src = "http://80.229.42.13:80/SnapshotJPEG?Resolution=640x480&amp;Quality=Clarity&amp;1700853676"
uuid = "56d229bb-a245-4b7c-bfde-91d9392e9fa2"
loop = true

[output]
dst = "rtmp://localhost/live"
scales = [ 360, 480, 720,]
